INSERT INTO t_community VALUES (t_community_SEQ.nextval, '오늘의 꿀팁', 'article_content 01', sysdate, 'jy', 0);
INSERT INTO t_community VALUES (t_community_SEQ.nextval, '안녕하세요', 'article_content 02', sysdate, 'jy', 0);
INSERT INTO t_community VALUES (t_community_SEQ.nextval, '반갑습니다', 'article_content 03', sysdate, 'yj', 0);
INSERT INTO t_community VALUES (t_community_SEQ.nextval, '공지입니다', 'article_content 04', sysdate, 'admin', 4);
INSERT INTO t_community VALUES (t_community_SEQ.nextval, '쿠키와 같이 즐기면 좋은 음료', '커피나 홍차, 말차와 즐기면 좋습니다', sysdate, 'hw', 5);
INSERT INTO t_community VALUES (t_community_SEQ.nextval, '콤부차', 'article_content 06', sysdate, 'sj', 6);
INSERT INTO t_community VALUES (t_community_SEQ.nextval, '오늘의 늬우스', 'article_content 07', sysdate, 'phs', 7);
INSERT INTO t_community VALUES (t_community_SEQ.nextval, '빵 맞있다', 'article_content 08', sysdate, 'hw', 8);
INSERT INTO t_community VALUES (t_community_SEQ.nextval, '생지 구매', 'article_content 09', sysdate, 'hs', 9);
INSERT INTO t_community VALUES (t_community_SEQ.nextval, '오늘의 꿀팁', 'article_content 10', sysdate, 'sj', 0);
INSERT INTO t_community VALUES (t_community_SEQ.nextval, '반가워요', 'article_content 11', sysdate, 'sj', 1);
INSERT INTO t_community VALUES (t_community_SEQ.nextval, '오늘의 글귀', 'article_content 12', sysdate, 'hw', 2);
INSERT INTO t_community VALUES (t_community_SEQ.nextval, '술빵', 'article_content 13', sysdate, 'phs', 3);
INSERT INTO t_community VALUES (t_community_SEQ.nextval, '옥시시', 'article_content 14', sysdate, 'hs', 4);
INSERT INTO t_community VALUES (t_community_SEQ.nextval, '개선사항', 'article_content 15', sysdate, 'yj', 5);
INSERT INTO t_community VALUES (t_community_SEQ.nextval, '쥐어짜내는 중', 'article_content 16', sysdate, 'jy', 6);
INSERT INTO t_community VALUES (t_community_SEQ.nextval, '커뮤니티', 'article_content 17', sysdate, 'jy', 7);
INSERT INTO t_community VALUES (t_community_SEQ.nextval, '내일 점심 뭐 먹지', 'article_content 18', sysdate, 'hw', 8);
INSERT INTO t_community VALUES (t_community_SEQ.nextval, '댓글 달아주세요', 'article_content 19', sysdate, 'hw', 9);
INSERT INTO t_community VALUES (t_community_SEQ.nextval, '럭키박스', 'article_content 20', sysdate, 'hw', 0);
INSERT INTO t_community VALUES (t_community_SEQ.nextval, '맛있는 빵', 'article_content 21', sysdate, 'hs', 1);
INSERT INTO t_community VALUES (t_community_SEQ.nextval, '마들렌', 'article_content 22', sysdate, 'hs', 32);
INSERT INTO t_community VALUES (t_community_SEQ.nextval, '옥수수빵', 'article_content 23', sysdate, 'hs', 3);
INSERT INTO t_community VALUES (t_community_SEQ.nextval, '맛있는 빵', 'article_content 24', sysdate, 'sj', 24);
INSERT INTO t_community VALUES (t_community_SEQ.nextval, '생지 구매', 'article_content 25', sysdate, 'admin', 5);
INSERT INTO t_community VALUES (t_community_SEQ.nextval, '오늘의 디저트', '레몬 아이싱을 한 마들렌과 얼그레이 밀크티', sysdate, 'admin', 26);
INSERT INTO t_community VALUES (t_community_SEQ.nextval, '내일 점심 뭐 먹지', 'article_content 27', sysdate, 'hw', 7);
INSERT INTO t_community VALUES (t_community_SEQ.nextval, '아이싱', 'article_content 28', sysdate, 'jy', 18);
INSERT INTO t_community VALUES (t_community_SEQ.nextval, '오늘의 글귀', 'article_content 29', sysdate, 'jy', 9);
INSERT INTO t_community VALUES (t_community_SEQ.nextval, '좋아하는 빵', 'article_content 30', sysdate, 'jy', 10);
INSERT INTO t_community VALUES (t_community_SEQ.nextval, '반갑습니다', 'article_content 31', sysdate, 'jy', 1);
INSERT INTO t_community VALUES (t_community_SEQ.nextval, '쿠키와 같이 즐기면 좋은 음료', 'article_content 32', sysdate, 'jy', 2);
INSERT INTO t_community VALUES (t_community_SEQ.nextval, '오븐과 에어프라이', 'article_content 33', sysdate, 'hw', 13);
INSERT INTO t_community VALUES (t_community_SEQ.nextval, '안녕하세요', 'article_content 34', sysdate, 'hw', 34);
INSERT INTO t_community VALUES (t_community_SEQ.nextval, '케익 맛있겠다', 'article_content 35', sysdate, 'hw', 5);
INSERT INTO t_community VALUES (t_community_SEQ.nextval, '핑거푸드', 'article_content 36', sysdate, 'sj', 36);
INSERT INTO t_community VALUES (t_community_SEQ.nextval, '오늘의 꿀팁', 'article_content 37', sysdate, 'hw', 27);
INSERT INTO t_community VALUES (t_community_SEQ.nextval, '티라미수 먹고 싶다', 'article_content 38', sysdate, 'hs', 8);
INSERT INTO t_community VALUES (t_community_SEQ.nextval, '안녕하세요', 'article_content 39', sysdate, 'sj', 9);
INSERT INTO t_community VALUES (t_community_SEQ.nextval, '좋아하는 빵', 'article_content 40', sysdate, 'yj', 20);
INSERT INTO t_community VALUES (t_community_SEQ.nextval, '역할 분담', 'article_content 41', sysdate, 'yj', 1);
INSERT INTO t_community VALUES (t_community_SEQ.nextval, '오늘의 꿀팁', 'article_content 42', sysdate, 'hw', 22);
INSERT INTO t_community VALUES (t_community_SEQ.nextval, '내일자 뉴스', 'article_content 43', sysdate, 'hs', 3);
INSERT INTO t_community VALUES (t_community_SEQ.nextval, '안녕하세요', 'article_content 44', sysdate, 'sj', 34);
INSERT INTO t_community VALUES (t_community_SEQ.nextval, '마들렌과 즐기면 좋은 차', 'article_content 45', sysdate, 'sj', 5);
INSERT INTO t_community VALUES (t_community_SEQ.nextval, '케익 만들기-1', 'article_content 46', sysdate, 'hw', 16);
INSERT INTO t_community VALUES (t_community_SEQ.nextval, '버터쿠키', 'article_content 47', sysdate, 'hs', 7);
INSERT INTO t_community VALUES (t_community_SEQ.nextval, '베이킹 기본익히기', 'article_content 48', sysdate, 'phs', 28);
INSERT INTO t_community VALUES (t_community_SEQ.nextval, '유의사항', 'article_content 49', sysdate, 'jy', 9);
INSERT INTO t_community VALUES (t_community_SEQ.nextval, '마들렌', 'article_content 50', sysdate, 'yj', 10);
INSERT INTO t_community VALUES (t_community_SEQ.nextval, '케익 케이크', 'article_content 51', sysdate, 'yj', 1);
INSERT INTO t_community VALUES (t_community_SEQ.nextval, '휘핑크림 생크림 설탕 함량', 'article_content 52', sysdate, 'jy', 2);
INSERT INTO t_community VALUES (t_community_SEQ.nextval, '크림빵', 'article_content 53', sysdate, 'jy', 43);
INSERT INTO t_community VALUES (t_community_SEQ.nextval, '케익 만들기-2', 'article_content 54', sysdate, 'hw', 4);
INSERT INTO t_community VALUES (t_community_SEQ.nextval, '반갑습니다', 'article_content 55', sysdate, 'yj', 35);
INSERT INTO t_community VALUES (t_community_SEQ.nextval, '케익 만들기-3', 'article_content 56', sysdate, 'hw', 6);
INSERT INTO t_community VALUES (t_community_SEQ.nextval, '내일 점심 뭐 먹지', 'article_content 57', sysdate, 'sj', 27);
INSERT INTO t_community VALUES (t_community_SEQ.nextval, '아이싱 적정량', 'article_content 58', sysdate, 'sj', 18);
INSERT INTO t_community VALUES (t_community_SEQ.nextval, '우유에 케이크 말아먹기', 'article_content 59', sysdate, 'sj', 9);
INSERT INTO t_community VALUES (t_community_SEQ.nextval, '오늘의 꿀팁', 'article_content 60', sysdate, 'admin', 6);